name: 'the world '
favicon: null
layout_spectrum: 0.34655
typography_spectrum: 0.37228283239528537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#020204'
    - '#aeaca0'
    - '#795c3d'
    - '#1c8466'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
